<a href="https://colab.research.google.com/github/NirranjanOfficial/grinding-lab/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Imports:

In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns   #used for statistical plotting
import sklearn #blahhh
print(torch.__version__)

2.6.0+cu124


**Introduction to Tensors:**



###Creating different dim values:

In [ ]:
#scalar tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim #to find the number of dim of the tensor which in this case is 0

0

In [ ]:
scalar.item()  #used to print out the item from the tensor

7

In [ ]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim  #it gives out 1 dim

1

In [ ]:
vector.shape   #where shape prints 2

torch.Size([2])

In [ ]:
#MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [6,7,8]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [6, 7, 8]]])

In [ ]:
TENSOR.shape  #it says 1 3x3 tensor is there

torch.Size([1, 3, 3])

In [ ]:
scalar_tensor = torch.tensor(5)
vector_tensor = torch.tensor([1, 2, 3])
matrix_tensor = torch.tensor([[1, 2], [3, 4]])
three_d_tensor = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(f"Scalar ndim: {scalar_tensor.ndim}")
print(f"Vector ndim: {vector_tensor.ndim}")
print(f"Matrix ndim: {matrix_tensor.ndim}")
print(f"3D tensor ndim: {three_d_tensor.ndim}")

Scalar ndim: 0
Vector ndim: 1
Matrix ndim: 2
3D tensor ndim: 3


###Random Tensor

Random tensors are usually created and then it is updated based on the requirement!

In [ ]:
random_tensor =torch.rand(3,3)
random_tensor #the datatype fo this is Float32 which is default until we specifty

tensor([[0.4695, 0.1204, 0.1765],
        [0.9586, 0.8871, 0.5742],
        [0.3272, 0.7339, 0.3139]])

In [ ]:
random_tensor.ndim  #based on the number of params i give the op is given...
                    #like if i give (1,2,3) 1T 2R 3C => i get ndim=3

2

In [ ]:
#Creating a random tensor with similar to image tensor
random_image_size_tensor = torch.rand(size=(3,224,224))  #Color channel, Height , Width
random_image_size_tensor.shape, random_image_size_tensor.ndim  #prints out the shape of the sensor[C,H,W] and ndim of it !

(torch.Size([3, 224, 224]), 3)

In [ ]:
#Zero tensor
zero_tensor = torch.zeros(3,3)
zero_tensor

#One tensor
one_tensor = torch.ones(3,3)
one_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
mat = zero_tensor * random_tensor
mat

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
###creating tensors within a range

In [ ]:
one2ten = torch.arange(0,11)
one2ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten0 = torch.zeros_like(one2ten)  #generates tensor of zeros with same shape as ip
ten0

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
###Experiment!!!!

ra = torch.rand(3,2,3)
sa = torch.rand_like(ra)  #created an similar tensor
wa = sa*ra
wa

tensor([[[0.0370, 0.2969, 0.0962],
         [0.0838, 0.1060, 0.3217]],

        [[0.0227, 0.2267, 0.6771],
         [0.0283, 0.0384, 0.2816]],

        [[0.1116, 0.2583, 0.5439],
         [0.1516, 0.6045, 0.2650]]])

###Tensor datatype:
[Datatypes available](https://docs.pytorch.org/docs/stable/tensors.html)

**Note: Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:**
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
tensor_float32 = torch.tensor([3.0,6.0,9.0],
                              dtype=torch.float32,  #means we can specify th e datatype here lie float32 or float16
                              device=None, #like where the tensor runs...CPU GPU CUDA
                              requires_grad=False) #whether or not to track gradients with this tensors operations
tensor_float32

tensor([3., 6., 9.])

In [ ]:
#we can convert one data type into anothr
tensor_float16 = tensor_float32.type(torch.float16)
tensor_float16

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
###Experiment!
ten16 = torch.tensor([1,2,3],
                     dtype=torch.uint32,
                     device=None,
                     requires_grad=False)
tens = ten16*tensor_float32
tens

#no issues..it works!

tensor([ 3., 12., 27.])

###Getting attributes info from the Tensor:

1.   Tensor dtype - tensor.dtype
2.   Tensor device - tensor.device
3.   Tensor shape - tensor.shape


In [ ]:
some = torch.rand(3,4)
print(some)
print(f"Datatype of tensor: {some.dtype}")
print(f"Shape of tensor: {some.shape}")
print(f"Device tensor is on: {some.device}")

tensor([[0.7566, 0.7547, 0.3218, 0.2177],
        [0.1406, 0.7596, 0.8620, 0.2014],
        [0.9707, 0.0823, 0.6775, 0.4512]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


###Manipulating Tensors:
Tensors operations like
addition
multiplication
division
mat multiplication

In [ ]:
qw = torch.tensor([1,2,3])
qw +12  #summs with each of the element in the tensor
qw = qw/10 #divs with each of the element in the tensor
qw = qw*10 #multiplies with each of the element in the tensor
#we also have builtin func like  torch.mul(qw,10) ,etc.,

Matrix multiplcation...n normal multiplication:

In [ ]:
qw = torch.tensor([1,2,3])
#qw = qw*10 #multiplies 10 with each of the element in the tensor
torch.matmul(qw,qw)  #it is used to multiply 2 different matrix (dot product )

tensor(14)

In [ ]:
###LETS look at how much time it will take...
%%time
value = 0
for i in range(len(qw)-1):
  value += qw[i] * qw[i]
print(value)

tensor(5)
CPU times: user 4.15 ms, sys: 1.02 ms, total: 5.17 ms
Wall time: 7.25 ms


In [ ]:
%%time
torch.matmul(qw,qw)

###instead we can also use @ for mtrix multiplication ie dot product!

CPU times: user 103 µs, sys: 17 µs, total: 120 µs
Wall time: 128 µs


tensor(14)

Matrix multiplication errors:
1.  The **inner dimentsions** must match!
    like (3,2) @ (3,2) wont work
    (2,3) @ (3,2) will work
  
2.  The shape if the final matrix will be in the dimension of **outer dimension**  

In [ ]:
#first rule of matmul:
#torch.matmul(torch.rand(3,2),torch.rand(3,3)) ==>error
torch.matmul(torch.rand(3,2),torch.rand(2,3))
#2nd rule of matrix mul:
torch.matmul(torch.rand(3,2),torch.rand(2,1)) #output will be like (3x1)

tensor([[0.5025],
        [0.6918],
        [0.3358]])

In [ ]:
tensorA = torch.tensor([[1,2],
                        [3,4],
                        [4,5]])
tensorB = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])
#torch.matmul(tensorA,tensorB)  #it wont work due to rule one...we can take transverse and do it!
torch.mm(tensorA,tensorB.T)  #it will work as we have taken Transverse
tensorB.T.shape, tensorB.shape
###if we chenk here we can see that it satifies both the condition!

(torch.Size([2, 3]), torch.Size([3, 2]))

###Finding the min , max,sem,etc.,(Tensor aggregation):

In [ ]:
x= torch.arange(0,100,10)  #this is RANGE func not arrange
x
x.dtype

torch.int64

In [ ]:
#to find min
torch.min(x), min(x)
#to find max
torch.max(x),max(x)
#to find mean IT REQUIRES FLOAT32 TO WORK
#we cant directly use x.mean() it will shw error ie wrong datatype, so we need to chage it
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()
#to find sum
#torch.sum(x),x.sum()

tensor(0)


###To find the position of those aggregations:

In [ ]:
#in normal list we use list.index(target_element)
x=torch.rand(2,3,3)
torch.max(x)
# torch.argmax(x)
# torch.argmin(x)
###in general for an 1D it will return value but for bigger tensors, it will just convert the tensor into 1D and return the answer

tensor(0.9290)

###Reshaping, Stacking, Squeezing, unsqueezing tensors:
1.  Reshaping - reshapes an input tensor to a defined shape
2. View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
3. Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
4.  Squeeze - removes all 1 dimensions from a tensor
5. Unsqueeze - add a 1 dimension to a target tensor
6.  Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
import torch
x= torch.arange(1,13)
x,x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]), torch.Size([12]))

In [ ]:
#lets add extra dimension => RESHAPING
x_reshaped = x.reshape(6,2)   #here the params should be in such a way that their product is the number of elements
x_reshaped,x_reshaped.shape

(tensor([[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8],
         [ 9, 10],
         [11, 12]]),
 torch.Size([6, 2]))

In [ ]:
#Change the view => VIEW
#THE MAIN THING TO REMBEMBER IS THAT X,Z WILL SHARE SAME MEMORY...SO CHANGES AFFCT
z = x.view(2,6)
z.shape,z
#z[:,0] = 5   #THIS WILL CHANGE EVERY 1ST ELEMNT TO 5
z,x

(tensor([[ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12]]),
 tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]))

In [ ]:
#Stack
x_stacked = torch.stack([x,x],dim=1)  #dim = 0 Horizontal stacking (2x12)
x_stacked,x_stacked.shape             #dim = 1 Vertical stacking   (12x2)

(tensor([[ 1,  1],
         [ 2,  2],
         [ 3,  3],
         [ 4,  4],
         [ 5,  5],
         [ 6,  6],
         [ 7,  7],
         [ 8,  8],
         [ 9,  9],
         [10, 10],
         [11, 11],
         [12, 12]]),
 torch.Size([12, 2]))

In [ ]:
#Squeezing...it just removes one from the paramenter and add it into one tensor
y=torch.rand(2,1,3)
y_squeezed = y.squeeze()

print(y.shape,y_squeezed.shape)
print("\n")
print(y,'\n',y_squeezed)


torch.Size([2, 1, 3]) torch.Size([2, 3])


tensor([[[0.2812, 0.4712, 0.7209]],

        [[0.6859, 0.6848, 0.7651]]]) 
 tensor([[0.2812, 0.4712, 0.7209],
        [0.6859, 0.6848, 0.7651]])


In [ ]:
#Unsqueezing
y_unsqueezed = y_squeezed.unsqueeze(dim=-3)
y_unsqueezed,y_unsqueezed.shape #it is used to give extra position to the tensor

#dim = 0 [1,2,3]   #dim = -1 [2,3,1]
#dim = 1 [2,1,3]   #dim = -2 [2,1,3]
#dim = 2 [2,3,1]   #dim = -3 [1,2,3]

(tensor([[[0.2812, 0.4712, 0.7209],
          [0.6859, 0.6848, 0.7651]]]),
 torch.Size([1, 2, 3]))

In [ ]:
#Permute is used to reorder an target tensor into an speicfied order
torch.permute(y,dims=(2,0,1))  #here 0,1,2 are the position value
x_original = torch.rand(244,244,3)   #HEIGHT,WIDTH,COLOR_CHANNELS
#lets try permute or change the order
x_permuted = x_original.permute(2,0,1)  #COLOR_CHANNELS,HEIGHT,WIDHT
x_original.shape,x_permuted.shape
###mainly used when we want to shift the order

(torch.Size([244, 244, 3]), torch.Size([3, 244, 244]))

###INDEXING:
one of the most important concept!
It is similar to working with numpy

In [ ]:
import torch
x=torch.arange(1,10).reshape(1,3,3)  # 1 (3x3) tensor
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[0] , x[0][2] , x[0][2][2]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([7, 8, 9]),
 tensor(9))

In [ ]:
#we can use : to select all of the target dimension
x[: ,0]
x[:,:,2]  #to print all the 2nd index value of 3rd dimension
x[:,:,1]   #it will be highly useful in matrix multiplication
x[0,0,:]  #[1,2,3]
x[:,:,2] #to print[3,6,9]

tensor([[3, 6, 9]])

###Pytorch & Numpy:
NumPy is a popular scientific Python numerical computing library.
And because of this, PyTorch has functionality to interact with it.
1.  Data in NumPy, want in PyTorch tensor -> torch.from_numpy (ndarray)
2.  PyTorch tensor -> NumPy -> torch. Tensor. numpy ( )

**NOTE: Numpy default datatype in float64...so it gets reflected in the tensor too!**

In [ ]:
import torch
import numpy as np
array  = np.arange(0,6)
tensor = torch.from_numpy(array)  #used to convert numpy -> tensor
tensor.reshape(1,2,3)  #just tried out reshaping
tensor.squeeze #sqeezed into 1dim
tensor.shape
tensor.type(torch.float32).dtype #manually converted the tpye
# numpya = torch.Tensor.numpy(tensor) #used to convert tensor -> numpy
# numpya

torch.float32

In [ ]:
#will it affect if i chnage the value of the numpy ?
array = array+1
array, tensor
#nope...no changses!

(array([2, 3, 4, 5, 6, 7]), tensor([0, 1, 2, 3, 4, 5]))

In [ ]:
tensorc = torch.rand(2,3,3)
numpyx = torch.Tensor.numpy(tensorc)
numpyx

array([[[0.35521126, 0.8728768 , 0.47687358],
        [0.28736925, 0.0579499 , 0.78184414],
        [0.14960611, 0.72627705, 0.37846917]],

       [[0.21843606, 0.1921897 , 0.8910819 ],
        [0.63411283, 0.69505316, 0.44429153],
        [0.49625158, 0.6893902 , 0.6672997 ]]], dtype=float32)

In [ ]:
tensorc = tensorc+1
numpyx,tensorc
#same...no changes will affect!

(array([[[0.35521126, 0.8728768 , 0.47687358],
         [0.28736925, 0.0579499 , 0.78184414],
         [0.14960611, 0.72627705, 0.37846917]],
 
        [[0.21843606, 0.1921897 , 0.8910819 ],
         [0.63411283, 0.69505316, 0.44429153],
         [0.49625158, 0.6893902 , 0.6672997 ]]], dtype=float32),
 tensor([[[3.3552, 3.8729, 3.4769],
          [3.2874, 3.0580, 3.7818],
          [3.1496, 3.7263, 3.3785]],
 
         [[3.2184, 3.1922, 3.8911],
          [3.6341, 3.6951, 3.4443],
          [3.4963, 3.6894, 3.6673]]]))

###REPRODUCABILITY:
In short how a neural network learns:
start with random numbers -> tensor operations -> update random numbers to try and make them
of the data -> again -> again -> again...
To reduce the randomness in neural networks and PyTorch comes the concept of a random seed.
Essentially what the random seed does is "flavour" the randomness.


In [ ]:
import torch
randA = torch.rand(3,4)
randB = torch.rand(3,4)
#print(randA,'\n',randB)
print(randA == randB)
print(f"tensor A is {randA} \n &  \n tensor b is {randB}")

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
tensor A is tensor([[0.0138, 0.0017, 0.3094, 0.4911],
        [0.1081, 0.2500, 0.6432, 0.2565],
        [0.6059, 0.4998, 0.1384, 0.4913]]) 
 &  
 tensor b is tensor([[0.7007, 0.3414, 0.4991, 0.3161],
        [0.4103, 0.7855, 0.3575, 0.7147],
        [0.0049, 0.9416, 0.8887, 0.1324]])


In [ ]:
#lets make some reproducable random tensor using random seed
RANDOM_SEED = 42  #it can be anything...but its and important to declare it!
torch.manual_seed(RANDOM_SEED)
randC = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)  #we need to give it before every code block!
randD = torch.rand(3,4)
print(randC == randD)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


###GPU setup for Pytorch:

In [ ]:
import torch
torch.cuda.is_available()
!nvidia-smi

Fri May  9 12:56:39 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   58C    P8             10W /   70W |       2MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
#setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device
#this means that is cuda available it will use that or else CPU
#torch.cuda.device_count() just count the no of devices!

'cuda'

###Creating / Putting Tensors &Models in GPU:

In [ ]:
#default it will be in CPU
import torch
tensor = torch.tensor([1,2,3])
tensor.device

device(type='cpu')

In [ ]:
#Lets move it into GPU
tensor_on_gpu = tensor.to(device)
tensor_on_gpu   #as we have spescifed to run on GPU, we it switches to GPU
#we get cuda0 which is index of the gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
#Numpy only works with CPU...so we need to switch between cpu and gpu
#tensor_on_gpu.numpy()  #it wont directly work

In [ ]:
tensor_on_cpu = tensor_on_gpu.cpu()
tensor_on_cpu.numpy()

array([1, 2, 3])

In [ ]:
###we are done with Fundamentals...all left is to practice the excercises!